### ISSUE TITLE
Map forks incorrectly

### ISSUE THREAD

**Issue by CJYate** [samfoo/noobhack#11]
I'm sure you'll have seen this problem already -- I'm finding the map tends to fork incorrectly. 

I am usually playing on NAO (if that makes any difference) and it _may_ be that coming out of the game and going back in causes an issue.  I'm not sure how to reproduce the problem reliably.

Here's an example...
http://postimage.org/image/2e33oo938/

**Comment by CJYate** [comment]
Also, as an aside, what's the significance of the red asterisks on the map?

**Comment by samfoo** [comment]
The red asterisks are intended to show that you haven't actually connected to a floor above that node. For example if you're on dlvl 1 and you fall through a trap door to 5; dlvl 5 would have a star above it, showing that you haven't explored what's above it.

As for the actual bug: It's been a long standing issue that's frustrated me terribly (so much that basically every test that's been written is for testing the mapping). There's so many edge cases... the biggest problem is that when you arrive on certain levels (specifically the mines), noobhack can't know that you're on the mines until it sees enough of the map revealed ... this complicates things.

I'll try to take a look at it tomorrow, but your existing saves will be corrupted since the map is stored in the save file. You can fix this by deleting everything in your ~/.noobhack directory.

**Comment by CJYate** [comment]
As it's a long standing issue, don't worry about trying to fix it ASAP! ... I have seen this problem with just levels 1,2,3 of the dungeon - before entering the mines. 

Do you think more test cases would help to identify a specific bug, or is this something that is always likely to be a tricky problem? I could probably contribute some more tests if I've a bit of time to analyse things...

No worries about that particular save though. I got my Monk killed at the bottom of the mines last night :-/  ;-)

**Comment by samfoo** [comment]
I believe this is fixed now. There's bound to be bugs in the new proper mapping, but at least now test cases can be written against it. Checkout the new 0.3 code and let me know how it works for you.

**Comment by CJYate** [comment]
Hi Sam,

Thanks. I'm looking at the 0.3 code now. Hardly worth a pull request, but FYI, I need to insert noobhack.ui into the 'packages' section of setup.py, or noobhack can't find the game module after it's been compiled...

Chris

**Comment by samfoo** [comment]
I'm on a long haul flight next week. I plan on getting proper pip/easy_install packages up at that point, I'll fix this then. After this release, I'll start working on features again. At least enough to match feature parity with interhack on the important stuff.

**Comment by CJYate** [comment]
Hey Sam,

When you're just generally testing stuff, do you bother compiling and
installing or just run the script against the python scripts? It's
quite possible I'm making things more complicated than I need to...

Chris

On 29 November 2011 23:36, Sam Gibson
reply@reply.github.com
wrote:

**Comment by samfoo** [comment]
Up until this "official-ish" release, I was just running the source directly. Today I tested the distribution by doing something like the following:

```
$ python setup.py sdist
$ pip install dist/noobhack-0.3.tar.gz
```

This should download the necessary eggs (viz. vt102) and install it. I would highly suggest using virtualenv if you're not already doing so. 

You should also be able to run:

```
$ python setup.py install
```

You were correct that it was missing the scripts, I've just been lazy about maintaining the setup script, but it should be working now.
