### ISSUE TITLE
Document some minor things please

### ISSUE THREAD

**Issue by TjrGithub** [samfoo/noobhack#2]
Please document some minor things:
1) You can't use the MSGTYPE option to configure away the messages "welcome (back) to nethack" and "restoring save file".

2) The installation & first run aren't fully coverend in the readme:
sudo easy_install vt102 #done, worked
unset PYTHONPATH
export PYTHONPATH=pwd:$PYTHONPATH:scripts/noobhack
cd ~/Downloads/samfoo-noobhack-499e536/
./scripts/noobhack --crumbs -h nethack.alt.org

3) How do you get around this runtime error if you're trying to convert to noobhack in the middle of a game? (I copied a file from a fresh game.)

4) Presumably, noobhack gets mixed up if you have several NAO accounts.

5) Neither DECgraphics nor IBMgraphics seem to work. I'm using an xterm on OS X and am playing on NAO.

6) An exhausting list of keystrokes it uses, because I remap movement keys with GNU screen to avoid accidentally breaking pacifist conduct

7) How reliably does it detect dungeon branch change? E.g. if you branchport into the quest and end up in one of the rooms-and-corridor levels?

**Comment by samfoo** [comment]
I added some of the documentation to a newly created [FAQ wiki page](https://github.com/samfoo/noobhack/wiki/FAQ). But more directly here's a response to your questions:

> How do you get around this runtime error if you're trying to convert to noobhack in the middle of a game? (I copied a file from a fresh game.)

At the moment you can't. I've debated changing this and if you'd really like it then I'll do it. The problem is that it makes branch detection basically impossible. There's no way for noobhack to know when you're starting a new game that you're in the Astral planes or Sokoban or something if it doesn't know where you came from. The result of this is likely going to be subtle bugs in how the dungeon graph is maintained (possibly breaking breadcrumbs and definitely breaking mapping).

> Presumably, noobhack gets mixed up if you have several NAO accounts.

Correct. I'm going to create a ticket for allowing you to specify a save file on the command line which will, at least, mitigate this problem.

> Neither DECgraphics nor IBMgraphics seem to work. I'm using an xterm on OS X and am playing on NAO.

Coming soon.

> An exhausting list of keystrokes it uses, because I remap movement keys with GNU screen to avoid accidentally breaking pacifist conduct

I'm trying to keep the keys down to an absolute minimum. Presently noobhack only uses two keys:
1. `tab`: This toggles the helper overlay.
2. ```: This toggles map view. Within map view `j` and `k` scroll up and down.

> How reliably does it detect dungeon branch change? E.g. if you branchport into the quest and end up in one of the rooms-and-corridor levels?

At the moment it's very reliable at the mines and at sokoban, but doesn't detect any other branches (including Ft. Ludios). This will change very soon and is a high priority.

More specifically: branchporting via the Eye is at the moment not detected and I'll need to implement it. 

Thanks for taking the time to write everything down. I'll try and get fixes out ASAP for your biggest issues (after work today).
